openapi: '3.0.2'

info:
  title: Case Law API
  version: '1.0'

servers:
- url: https://{environment}.caselaw.nationalarchives.gov.uk/v1
  variables:
    environment:
      default: api
      enum:
        - api         # Production
        - api.staging # Staging

security:
  - { basic: [] }

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
      description: HTTP Basic Authentication
  parameters:
    judgmentUri:
      name: judgmentUri
      in: path
      required: true
      schema:
        type: string
  responses:
    judgment:
      description: A single judgment document, in Akoma Ntoso XML

paths:
  /status:
    get:
      summary: Health check
      description: |
        A test endpoint that can be used by clients to verify service availability, and to verify valid authentication credentials.
        Authentication is not required, but if it is provided, it will be checked for validity.
      tags:
        - Status
      responses:
        '200':
          description: The service is available, and if authentication was provided, the authentication is valid.
        '401':
          description: The service is available, but the provided authentication was not valid.
      security:
        - {}
        - { basic: [] }
  /{judgmentUri}:
    get:
      summary: Read a judgment or decision, given its URI
      operationId: getDocumentByUri
      tags:
        - Reading
      parameters:
        - $ref: "#/components/parameters/judgmentUri"
      responses:
        '200':
          $ref: "#/components/responses/judgment"
